
# Vox3DSpace source file listing variables.
macro(build_projects_sources)
  list(
    APPEND
      vox3dspace_common_base_sources
      "${vox3dspace_src_root}/common/base/commonDef.h"
      "${vox3dspace_src_root}/common/base/commonType.h"
      "${vox3dspace_src_root}/common/base/preCompileDef.cc"
      "${vox3dspace_src_root}/common/base/preCompileDef.h"
    )
  list(
    APPEND
      vox3dspace_common_math_sources
      "${vox3dspace_src_root}/common/math/Box.cc"
      "${vox3dspace_src_root}/common/math/Box.h"
      "${vox3dspace_src_root}/common/math/half.h"
      "${vox3dspace_src_root}/common/math/mat2.h"
      "${vox3dspace_src_root}/common/math/mat3.h"
      "${vox3dspace_src_root}/common/math/mat4.h"
      "${vox3dspace_src_root}/common/math/math.cc"
      "${vox3dspace_src_root}/common/math/math.h"
      "${vox3dspace_src_root}/common/math/mathutil.cc"
      "${vox3dspace_src_root}/common/math/mathutil.h"
      "${vox3dspace_src_root}/common/math/mdefine.h"
      "${vox3dspace_src_root}/common/math/Plane.cc"
      "${vox3dspace_src_root}/common/math/Plane.h"
      "${vox3dspace_src_root}/common/math/quat.h"
      "${vox3dspace_src_root}/common/math/Ray.h"
      "${vox3dspace_src_root}/common/math/scalar.h"
      "${vox3dspace_src_root}/common/math/Sphere.h"
      "${vox3dspace_src_root}/common/math/TMatHelpers.h"
      "${vox3dspace_src_root}/common/math/TQuatHelpers.h"
      "${vox3dspace_src_root}/common/math/TVecHelpers.h"
      "${vox3dspace_src_root}/common/math/vec2.h"
      "${vox3dspace_src_root}/common/math/vec3.h"
      "${vox3dspace_src_root}/common/math/vec4.h"
    )
  list(
      APPEND
        vox3dspace_engine_data_stream_sources
        "${vox3dspace_src_root}/voxengine/data/stream/streamDef.h"
        "${vox3dspace_src_root}/voxengine/data/stream/ArrayBuffer.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/ArrayBuffer.h"
        "${vox3dspace_src_root}/voxengine/data/stream/DataView.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/DataView.h"
        "${vox3dspace_src_root}/voxengine/data/stream/BaseTypeArray.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Float32Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Float32Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Int8Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Int8Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Int16Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Int16Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Int32Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Int32Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Uint8Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Uint8Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Uint16Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Uint16Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/Uint32Array.cc"
        "${vox3dspace_src_root}/voxengine/data/stream/Uint32Array.h"
        "${vox3dspace_src_root}/voxengine/data/stream/streamDemo.h"
      )    
  list(
    APPEND
      vox3dspace_engine_data_ctm_sources
      "${vox3dspace_src_root}/voxengine/data/ctm/ctmDef.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ctmUtils.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ctmDemo.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTM.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTM.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTMFile.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTMFile.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTMFileBody.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTMFileBody.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTMStream.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/CTMStream.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/FileHeader.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/FileHeader.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/FileMG2Header.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/FileMG2Header.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ICTMRStream.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ICTMWStream.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/IDecoder.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/InterleavedStream.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/InterleavedStream.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/IReaderHeader.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/LZMA.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/LZMA.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/OutWindow.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/OutWindow.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/RangeDecoder.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/RangeDecoder.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ReaderMG1.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/ReaderMG1.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ReaderMG2.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/ReaderMG2.h"
      "${vox3dspace_src_root}/voxengine/data/ctm/ReaderRAW.cc"
      "${vox3dspace_src_root}/voxengine/data/ctm/ReaderRAW.h"
    )

  list(
    APPEND
    vox3dspace_engine_math_sources
      "${vox3dspace_src_root}/voxengine/math/mathDefine.h"
      "${vox3dspace_src_root}/voxengine/math/Float.h"
      "${vox3dspace_src_root}/voxengine/math/vec2.cc"
      "${vox3dspace_src_root}/voxengine/math/vec2.h"
      "${vox3dspace_src_root}/voxengine/math/vec3.cc"
      "${vox3dspace_src_root}/voxengine/math/vec3.h"
      "${vox3dspace_src_root}/voxengine/math/EulerOrder.h"
      "${vox3dspace_src_root}/voxengine/math/IEuler.h"
      "${vox3dspace_src_root}/voxengine/math/Euler.cc"
      "${vox3dspace_src_root}/voxengine/math/Euler.h"
      "${vox3dspace_src_root}/voxengine/math/IMatrix4.h"
      "${vox3dspace_src_root}/voxengine/math/Matrix4.cc"
      "${vox3dspace_src_root}/voxengine/math/Matrix4.h"
      "${vox3dspace_src_root}/voxengine/math/OBB.cc"
      "${vox3dspace_src_root}/voxengine/math/OBB.h"
    )
  list(
    APPEND
    vox3dspace_engine_text_sources
      "${vox3dspace_src_root}/voxengine/text/BaseText.cc"
      "${vox3dspace_src_root}/voxengine/text/BaseText.h"
  )
  list(
    APPEND
    vox3dspace_engine_view_sources
      "${vox3dspace_src_root}/voxengine/view/Camera.cc"
      "${vox3dspace_src_root}/voxengine/view/Camera.h"
  )
  list(
    APPEND
    vox3dspace_profile_sources
      "${vox3dspace_src_root}/profile/log/color/consoleColor.cc"
      "${vox3dspace_src_root}/profile/log/color/consoleColor.h"
      "${vox3dspace_src_root}/profile/log/def/dllmain.cc"
      "${vox3dspace_src_root}/profile/log/def/framework.h"
      "${vox3dspace_src_root}/profile/log/def/pch.cc"
      "${vox3dspace_src_root}/profile/log/def/pch.h"
  )
endmacro()